CREATE TABLE QUES_TYPE
(
ID INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
Q_TYPE ENUM('FILL UPS','MULTIPLE CHOICE', 'ONE WORD ANSWER') NOT NULL,
IS_ACTIVE BOOLEAN DEFAULT 1
);
CREATE TABLE QUESTION
(
ID INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
Q_TEXT VARCHAR(1000) NOT NULL,
Q_TYPE_ID INT UNSIGNED NOT NULL,
Q_SCORE INT UNSIGNED,
FOREIGN KEY (Q_TYPE_ID) REFERENCES QUES_TYPE(ID) 
);

CREATE TABLE QUES_ANS_OPT
(
ID INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
ANS_TEXT VARCHAR(500) NOT NULL,
Q_TEXT_ID INT UNSIGNED NOT NULL,
SCORE INT DEFAULT 1,
FOREIGN KEY(Q_TEXT_ID) REFERENCES QUESTION(ID)
);
CREATE TABLE QUES_CORRECT_ANS
(
ID INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
QUES_ID INT UNSIGNED NOT NULL,
Q_ANS_OPT_ID INT UNSIGNED NOT NULL,
FOREIGN KEY(QUES_ID) REFERENCES QUESTION(ID),
FOREIGN KEY(Q_ANS_OPT_ID) REFERENCES QUES_ANS_OPT(ID),
UNIQUE(QUES_ID,Q_ANS_OPT_ID)
);

SELECT * FROM QUES_CORRECT_ANS;
CREATE TABLE ASSESMENT
(
ID INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
NAME VARCHAR(200) NOT NULL UNIQUE
);
CREATE TABLE ASSES_QUESTION
(
ID INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
ASSES_ID INT UNSIGNED NOT NULL,
QUES_TEXT_ID INT UNSIGNED NOT NULL,
FOREIGN KEY(ASSES_ID) REFERENCES ASSESMENT(ID),
FOREIGN KEY(QUES_TEXT_ID) REFERENCES QUESTION(ID)
); 
SELECT * FROM ASSESMENT;
SELECT * FROM ASSES_QUESTION;
SELECT Q.ID,Q.Q_TEXT FROM QUESTION Q, QUES_TYPE QT WHERE Q.ID NOT IN(SELECT QUES_TEXT_ID FROM ASSES_QUESTION WHERE ASSES_ID=1)AND QT.IS_ACTIVE=1 AND QT.ID=Q.Q_TYPE_ID;
INSERT INTO ASSES_QUESTION(ASSES_ID,QUES_TEXT_ID) VALUES(1,2);

ALTER TABLE QUES_TYPE ADD UNIQUE(Q_TYPE);

ALTER TABLE ASSES_QUESTION ADD UNIQUE(ASSES_ID,QUES_TEXT_ID);
SELECT QO.ANS_TEXT, QO.Q_TEXT_ID FROM QUES_ANS_OPT QO, QUES_TYPE QT, QUESTION Q WHERE Q_TEXT_ID= 6 AND QT.Q_TYPE !='ONE WORD ANSWER' AND QT.ID=Q.Q_TYPE_ID AND Q.ID=QO.Q_TEXT_ID;
SELECT * FROM QUES_TYPE;
SELECT * FROM QUESTION;
SELECT * FROM QUES_ANS_OPT;
